---
#
# Ansible managed
#
repository:
  description: Install and configure ara api on your system.
  homepage: https://buluma.github.io/
  topics: ansible, records, ara, reports, cloud, development, monitoring, reporting, ansible, molecule, tox, playbook, hacktoberfest
